### PR TITLE
Changes tabs to spaces

### PR DESCRIPTION
**Pull request by thomas-daniels**
PEP recommends 4 spaces for indentation, no tabs.

### CODE REVIEW

**Comment by Kubo2** [comment]
@ProgramFOX So you could also add a `CONTRIBUTING.md` to further notify about the coding style.

**Comment by thomas-daniels** [comment]
@Kubo2 Good idea, I'll do that!

**Comment by thomas-daniels** [comment]
@Kubo2 Done, I added CONTRIBUTING.md.

@michaelpri10 @Jacob-Gray Please check CONTRIBUTING.md and share any comments, if you have. If you think it's good, don't forget to follow the rules when committing, it would be a shame if we wouldn't follow our own guidelines :P

**Comment by Kubo2** [comment]
@ProgramFOX :+1:

**Pull request merged**
